### ISSUE TITLE
FreeNAS iocage Plugin 

### ISSUE THREAD

**Issue by gt2416** [Nekmo/amazon-dash#120]
Using the plugin, amazon-dash service does not start. It results in this error :

```
File "/usr/local/lib/python3.6/site-packages/scapy/arch/__init__.py", line 63, in <module>
    conf.use_bpf = True
  File "/usr/local/lib/python3.6/site-packages/scapy/config.py", line 75, in __set__
    self.hook(self.name, val, *self.args, **self.kargs)
  File "/usr/local/lib/python3.6/site-packages/scapy/config.py", line 491, in _socket_changer
    _set_conf_sockets()
  File "/usr/local/lib/python3.6/site-packages/scapy/config.py", line 436, in _set_conf_sockets
    raise ScapyInvalidPlatformException("Darwin (OSX) only !")
scapy.error.ScapyInvalidPlatformException: Darwin (OSX) only !
```
It also spits out the same error if installed manually.

I think only the last few lines are relevant, I have not touched anything, just installed the plugin and added 1 Homeassistant command in the xml file. 

Another question, In the config file, where it says legacy-api for HomeAssistant, is that where you put the newer access token ?
 Thanks

**Comment by gt2416** [comment]
Thanks for the fast response. 
The updated plugin works now 👍

**Comment by tprelog** [comment]
> I just recreated the plugin and it works. (after using the wget to get the new scapy file)
Not sure why my original jail is spitting out errors. The only difference was that instead of dhcp I assigned it a ipv4 address

I'm pretty sure this a FreeNAS (iocage) issue. In general I've seen others report issues when trying to set an assigned IP address during creation. It seems like this works just fine for some people but for others it does not. I've always had good luck using the `dhcp=on vnet=on bpf=yes` options. Also I've seen others suggest these options when setting an IP manually fails to work. Besides I find (in my opinion) it much easier to manage IP address in one place, on my router, rather than multiple computers, VMs, and(or) jails

**Comment by Nekmo** [comment]
Thanks for the notice! it may be a bug in Scapy. I'll wait for a patched version.
